-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('SONG_FROZEN', 'UNFREEZE_REQUESTED', 'UNFREEZE_APPROVED', 'UNFREEZE_DENIED', 'TAKE_UPLOADED', 'TAKE_PROMOTED', 'APPROVAL_GIVEN', 'MIX_CREATED', 'MIX_FINALIZED', 'DOWNLOAD_WORKING_PULL', 'DOWNLOAD_HANDOFF', 'DOWNLOAD_ARCHIVE', 'TODO_CREATED', 'TODO_COMPLETED');

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "action" "AuditAction" NOT NULL,
    "actorId" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
